Imoporting all important libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

Load Dataset

In [2]:
df = pd.read_csv("C:\\Users\\Asus\\Clone files\\Data_Driven_Water_Quality_Surveilance_And_Loss_Detection_System\\technical\\datasets\\water_quality_clean.csv")
print("Dataset Loaded Successfully")
df.head()

Dataset Loaded Successfully

,sensor_id,timestamp,location_id,pH,turbidity,TDS,DO,flow_rate,pressure,alert_flag
0,SNS-LOCA01-001,2025-05-01T00:00:00Z,ZONE-A,7.30,1.01,232.71,7.60,12.79,347.65,NaN
1,SNS-LOCA02-002,2025-05-01T00:00:00Z,ZONE-A,7.22,1.83,229.58,8.14,13.55,353.83,NaN
2,SNS-LOCB01-001,2025-05-01T00:00:00Z,ZONE-B,7.11,1.21,212.95,8.20,12.62,368.69,NaN
3,SNS-LOCB02-002,2025-05-01T00:00:00Z,ZONE-B,7.08,1.06,231.53,8.57,13.40,356.69,NaN
4,SNS-LOCC01-001,2025-05-01T00:00:00Z,ZONE-C,7.41,1.46,198.66,7.79,13.86,338.45,NaN

DATASET INFORMATION

In [3]:
print("Dataset Shape:", df.shape)
print("\nDataset Columns:", df.columns)
print("\nData Types:", df.dtypes)
print("\nDataset Info:")
df.info()

Dataset Shape: (17280, 10)

Dataset Columns: Index(['sensor_id', 'timestamp', 'location_id', 'pH', 'turbidity', 'TDS', 'DO',
       'flow_rate', 'pressure', 'alert_flag'],
      dtype='object')

Data Types: sensor_id       object
timestamp       object
location_id     object
pH             float64
turbidity      float64
TDS            float64
DO             float64
flow_rate      float64
pressure       float64
alert_flag      object
dtype: object

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17280 entries, 0 to 17279
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sensor_id    17280 non-null  object
 1   timestamp    17280 non-null  object
 2   location_id  17280 non-null  object
 3   pH           17280 non-null  float64
 4   turbidity    17280 non-null  float64
 5   TDS          17280 non-null  float64
 6   DO           17280 non-null  float64
 7   flow_rate    17280 non-null  float64
 8   pressure     17280 non-null  float64
 9   alert_flag   169 non-null    object
dtypes: float64(6), object(4)
memory usage: 1.3+ MB

STATISTICQL SUMMARY OF THE DATASET

In [4]:
df.describe()

,pH,turbidity,TDS,DO,flow_rate,pressure
count,17280.000000,17280.000000,17280.000000,17280.000000,17280.000000,17280.000000
mean,7.199883,1.506184,221.133760,8.004267,15.429931,349.627622
std,0.160445,0.440502,28.689149,0.401943,1.919588,9.716227
min,5.510000,0.060000,146.150000,6.430000,9.440000,216.670000
25%,7.100000,1.230000,209.600000,7.730000,14.080000,344.470000
50%,7.200000,1.500000,219.835000,8.000000,15.380000,349.910000
75%,7.300000,1.770000,230.100000,8.280000,16.700000,355.350000
max,7.780000,11.750000,791.940000,9.910000,32.770000,380.640000

CHECK MISSING VALUES

In [5]:
missing = df.isnull().sum()
missing_df = pd.DataFrame({'column_name': df.columns, 'missing_values': missing})   
print("\nMissing Values:")
print(missing_df)

Missing Values:
             column_name  missing_values
sensor_id      sensor_id               0
timestamp      timestamp               0
location_id  location_id               0
pH                    pH               0
turbidity      turbidity               0
TDS                  TDS               0
DO                    DO               0
flow_rate      flow_rate               0
pressure        pressure               0
alert_flag    alert_flag           17111

In [6]:
df['alert_flag'] = df['alert_flag'].fillna('normal')

In [7]:
missing = df.isnull().sum()
missing_df = pd.DataFrame({'column_name': df.columns, 'missing_values': missing})   
print("\nMissing Values:")
print(missing_df)

Missing Values:
             column_name  missing_values
sensor_id      sensor_id               0
timestamp      timestamp               0
location_id  location_id               0
pH                    pH               0
turbidity      turbidity               0
TDS                  TDS               0
DO                    DO               0
flow_rate      flow_rate               0
pressure        pressure               0
alert_flag    alert_flag               0

CHECK DUPLICATES

In [8]:
duplicates =df.duplicated().sum()
print("\nNumber of Duplicate Rows:", duplicates)

Number of Duplicate Rows: 0

CONVERT TIMESTEPS

In [9]:
df['timestamp'] = pd.to_datetime(df['timestamp'],errors='coerce')
df['timestamp'].head()

0   2025-05-01 00:00:00+00:00
1   2025-05-01 00:00:00+00:00
2   2025-05-01 00:00:00+00:00
3   2025-05-01 00:00:00+00:00
4   2025-05-01 00:00:00+00:00
Name: timestamp, dtype: datetime64[ns, UTC]

Check Invalid Timestamps

In [10]:
invalid_timestamp = df['timestamp'].isnull().sum()

print("Invalid timestamps:", invalid_timestamp)

Invalid timestamps: 0

Sensor Validation

In [11]:
print("Unique Sensors:",
      df['sensor_id'].nunique())

print("Unique Locations:",
      df['location_id'].nunique())

print("Unique Sensor names:", df['sensor_id'].unique())
print("Unique Location names:", df['location_id'].unique())

Unique Sensors: 6
Unique Locations: 3
Unique Sensor names: ['SNS-LOCA01-001' 'SNS-LOCA02-002' 'SNS-LOCB01-001' 'SNS-LOCB02-002'
 'SNS-LOCC01-001' 'SNS-LOCC02-002']
Unique Location names: ['ZONE-A' 'ZONE-B' 'ZONE-C']

Check Sensor Frequency

In [12]:
sensor_frequency = (
    df.groupby('sensor_id')
      .size()
      .sort_values(ascending=False)
)

sensor_frequency.head()

sensor_id
SNS-LOCA01-001    2880
SNS-LOCA02-002    2880
SNS-LOCB01-001    2880
SNS-LOCB02-002    2880
SNS-LOCC01-001    2880
dtype: int64

Check Alert Flag

In [13]:
print(
    df['alert_flag']
    .value_counts(dropna=False)
)

alert_flag
normal                              17111
leak_suspected                         79
wq_anomaly_tds_spike                   50
wq_anomaly_contamination_ph_drop       30
wq_anomaly_turbidity_spike             10
Name: count, dtype: int64

CONTAMINATION LABEL

In [14]:
contamination_labels = [
    'wq_anomaly_tds_spike',
    'wq_anomaly_contamination_ph_drop',
    'wq_anomaly_turbidity_spike'
]

df['contamination_target'] = (
    df['alert_flag']
    .isin(contamination_labels)
    .astype(int)
)

LEAK LABEL

In [15]:
df['leak_target'] = (
    df['alert_flag']
    == 'leak_suspected'
).astype(int)

In [16]:
print("\nContamination Distribution:")
print(df['contamination_target'].value_counts())

print("\nLeak Distribution:")
print(df['leak_target'].value_counts())

Contamination Distribution:
contamination_target
0    17190
1       90
Name: count, dtype: int64

Leak Distribution:
leak_target
0    17201
1       79
Name: count, dtype: int64

In [17]:
missing = df.isnull().sum()
missing_df = pd.DataFrame({'column_name': df.columns, 'missing_values': missing})   
print("\nMissing Values:")
print(missing_df)

Missing Values:
                               column_name  missing_values
sensor_id                        sensor_id               0
timestamp                        timestamp               0
location_id                    location_id               0
pH                                      pH               0
turbidity                        turbidity               0
TDS                                    TDS               0
DO                                      DO               0
flow_rate                        flow_rate               0
pressure                          pressure               0
alert_flag                      alert_flag               0
contamination_target  contamination_target               0
leak_target                    leak_target               0

Validate Water Quality Values

In [18]:
print("pH Range:")
print(df['pH'].min(),
      df['pH'].max())

print("\nTurbidity Range:")
print(df['turbidity'].min(),
      df['turbidity'].max())

print("\nTDS Range:")
print(df['TDS'].min(),
      df['TDS'].max())

print("\nDO Range:")
print(df['DO'].min(),
      df['DO'].max())

pH Range:
5.51 7.78

Turbidity Range:
0.06 11.75

TDS Range:
146.15 791.94

DO Range:
6.43 9.91

Final Validation

In [19]:
print(df.isnull().sum())

sensor_id               0
timestamp               0
location_id             0
pH                      0
turbidity               0
TDS                     0
DO                      0
flow_rate               0
pressure                0
alert_flag              0
contamination_target    0
leak_target             0
dtype: int64

In [21]:
df.to_csv(
    "cleaned_sensor_data.csv",
    index=False
)

print("Cleaned dataset saved successfully")

Cleaned dataset saved successfully

In [22]:
report = f"""
=========================
DATA VALIDATION REPORT
=========================

Rows: {df.shape[0]}
Columns: {df.shape[1]}

Unique Sensors:
{df['sensor_id'].nunique()}

Unique Locations:
{df['location_id'].nunique()}

Duplicate Rows:
{duplicates}

Missing Values:
{df.isnull().sum()}

Contamination Cases:
{df['contamination_target'].sum()}

Leak Cases:
{df['leak_target'].sum()}

Dataset Status:
READY FOR EDA
"""

print(report)

with open(
    "validation_report.md",
    "w"
) as f:
    f.write(report)

=========================
DATA VALIDATION REPORT
=========================

Rows: 17280
Columns: 12

Unique Sensors:
6

Unique Locations:
3

Duplicate Rows:
0

Missing Values:
sensor_id               0
timestamp               0
location_id             0
pH                      0
turbidity               0
TDS                     0
DO                      0
flow_rate               0
pressure                0
alert_flag              0
contamination_target    0
leak_target             0
dtype: int64

Contamination Cases:
90

Leak Cases:
79

Dataset Status:
READY FOR EDA